# Generated by Django 5.2.5 on 2025-08-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=120, unique=True)),
                ('current_stock', models.IntegerField(default=0)),
                ('average_daily_sales', models.FloatField(default=0.0)),
            ],
        ),
    ]
