# Generated by Django 5.2.4 on 2025-09-30 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_stocktransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransaction",
            name="product_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="inventory.inventoryproduct",
            ),
        ),
    ]
