# Generated by Django 5.2.6 on 2025-10-03 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_stocktransaction_product_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocktransaction",
            name="product_name",
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="inventory.inventoryproduct",
            ),
            preserve_default=False,
        ),
    ]
