# Generated by Django 5.2.6 on 2025-10-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_remove_stocktransaction_product_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryproduct",
            name="category",
        ),
        migrations.RemoveField(
            model_name="inventoryproduct",
            name="description",
        ),
        migrations.RemoveField(
            model_name="inventoryproduct",
            name="price",
        ),
        migrations.RemoveField(
            model_name="inventoryproduct",
            name="supplier",
        ),
        migrations.AddField(
            model_name="inventoryproduct",
            name="sku",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
