# Generated by Django 5.2.6 on 2025-10-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_remove_inventoryproduct_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryproduct",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
