# Generated by Django 5.2.6 on 2025-10-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_alter_inventoryproduct_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryproduct",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
