# Generated by Django 5.2.6 on 2025-09-22 03:42

from django.db import migrations



def copy_quantity_to_inventory(apps, schema_editor):
    Product = apps.get_model("product_app", "Product")
    Inventory = apps.get_model("product_app", "Inventory")

    for product in Product.objects.all():
        inv, created = Inventory.objects.get_or_create(product=product)
        inv.total_stock = product.quantity
        inv.stock_in = product.quantity  # assume all stock was received initially
        inv.stock_out = 0
        inv.save()

class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_inventory'),
    ]

    operations = [
        migrations.RunPython(copy_quantity_to_inventory, reverse_code=migrations.RunPython.noop),
    ]
