# Generated by Django 5.2.6 on 2025-09-22 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_auto_20250922_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
