# Generated by Django 5.2.6 on 2025-10-06 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_supplier_product_supplier_saleshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, help_text="Relative path, e.g., 'products/gray_pants.png'", max_length=500),
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(help_text="e.g., 'Christmas', 'Summer'", max_length=50)),
                ('keywords', models.TextField(help_text="Comma-separated trends, e.g., 'red sweaters, festive patterns'")),
                ('popularity_score', models.FloatField(default=0.0, help_text='From scrape, e.g., like count / 100')),
                ('hot_score', models.FloatField(default=0.0, help_text='Pre-computed: frequency * popularity (for predictions)')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('source_url', models.URLField(blank=True, help_text='Original trend page')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='product_app.category')),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
    ]
