# Generated by Django 5.2.6 on 2025-10-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_alter_product_image_url_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='source_name',
            field=models.CharField(blank=True, help_text='Source site, e.g., Vogue', max_length=100),
        ),
    ]
