# Generated by Django 5.2.6 on 2025-10-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_trend_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
